---
- name: Install Apache and Git
  hosts: webservers
  become: yes
  tasks:
    - name: Update the package index
      apt:
        update_cache: yes

    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Ensure Git is installed
      apt:
        name: git
        state: latest

- name: Update LB server
  hosts: database
  become: yes
  tasks:
    - name: Update the package index
      apt: 
        update_cache: yes
    
    - name: Ensure Git is installed
      apt:
        name: git
        state: latest
    
    - name: Install MySQL client
      apt:
        name: mysql-common
        state: latest
     
    - name: Ensure Wireshark is at the latest version
      apt:
        name: wireshark
        state: latest